/**
 * Label → 3D model registry.
 *
 * The scene graph never names a file. It names a LABEL ("sofa") and gives a
 * metric bounding box, and that is true whether the object was detected by the
 * reconstruction pipeline, generated by Imagine, or hand-authored in the demo
 * fixture. So the mapping from meaning to mesh belongs here, in one table, and
 * anything without an entry keeps the procedural box.
 *
 * Assets: Kenney "Furniture Kit", CC0 (public domain). No attribution is
 * legally required; it is in public/CREDITS.md anyway because saying where
 * your art came from is just correct. Licence text ships alongside the models
 * at public/models/kenney/LICENSE.txt.
 *
 * Why these are NOT Draco-compressed: the whole set is 187 KB uncompressed for
 * 18 models. A Draco decoder is ~200 KB of WASM on its own, so compressing
 * here would make the page bigger, not smaller. Revisit only if photoreal
 * models with real textures replace these.
 */

export type FitMode = "stretch" | "contain";

export interface ModelEntry {
  url: string;
  /**
   * How the model is fitted to the scene graph's box.
   *
   * `stretch` (default) scales each axis independently so the model occupies
   * EXACTLY the detected volume. That matters more than it sounds: that box is
   * the volume A* inflates and avoids, so a visual that overflows it is a
   * robot that appears to drive through the sofa it correctly planned around.
   *
   * `contain` keeps the model's proportions and fits it inside the box
   * instead. Use it for shapes whose silhouette is the whole point and which
   * look broken when stretched.
   */
  fit?: FitMode;
  /** Extra yaw in radians, for models authored facing an unexpected way. */
  yawOffset?: number;
  /**
   * Set false to keep the model's own materials instead of recolouring to the
   * scene graph's colour. Worth it when a model's colours carry information
   * the flat scene-graph swatch cannot — a plant is green leaves in a
   * terracotta pot, not one green.
   */
  tint?: boolean;
}

const K = "/models/kenney";

export const MODEL_REGISTRY: Record<string, ModelEntry> = {
  // ── the demo room ──
  table: { url: `${K}/table.glb` },
  chair: { url: `${K}/chairCushion.glb` },
  sofa: { url: `${K}/loungeSofa.glb` },
  shelf: { url: `${K}/bookcaseOpen.glb` },
  potted_plant: { url: `${K}/pottedPlant.glb`, fit: "contain", tint: false },
  rug: { url: `${K}/rugRectangle.glb` },
  tv: { url: `${K}/televisionModern.glb` },
  lamp: { url: `${K}/lampRoundFloor.glb`, fit: "contain" },

  // ── labels the reconstruction and Imagine paths can also emit ──
  desk: { url: `${K}/desk.glb` },
  bed: { url: `${K}/bedDouble.glb` },
  bench: { url: `${K}/bench.glb` },
  stool: { url: `${K}/stoolBar.glb`, fit: "contain" },
  fridge: { url: `${K}/kitchenFridge.glb` },
  side_table: { url: `${K}/sideTable.glb` },
  laptop: { url: `${K}/laptop.glb`, fit: "contain" },
  book: { url: `${K}/books.glb`, fit: "contain" },
  trashcan: { url: `${K}/trashcan.glb`, fit: "contain" },
  cabinet: { url: `${K}/cabinetTelevision.glb` },
};

/**
 * Resolve a label to a model.
 *
 * Falls back through the head noun, so `wooden_chair` and `dining_table` —
 * which the size-prior classifier and Imagine both produce — find `chair` and
 * `table` instead of dropping to a grey box. Same bridging rule the retrieval
 * layer uses for `by_label`, kept consistent on purpose.
 */
export function modelFor(label: string): ModelEntry | undefined {
  const key = label.toLowerCase().replace(/\s+/g, "_");
  if (MODEL_REGISTRY[key]) return MODEL_REGISTRY[key];
  const head = key.split("_").pop();
  return head ? MODEL_REGISTRY[head] : undefined;
}

/** Every distinct URL a set of labels needs — used to preload up front. */
export function urlsForLabels(labels: Iterable<string>): string[] {
  const out = new Set<string>();
  for (const l of labels) {
    const e = modelFor(l);
    if (e) out.add(e.url);
  }
  return [...out];
}
